import { LoanApplicationInput } from "./types";

export interface PresetProfile {
  id: string;
  name: string;
  badge: string;
  description: string;
  data: LoanApplicationInput;
}

export const PRESET_PROFILES: PresetProfile[] = [
  {
    id: "prime",
    name: "Prime Professional",
    badge: "Expected: Eligible",
    description: "Senior engineer at MNC with high credit score (780) and low existing debt.",
    data: {
      age: 34,
      gender: "Male",
      marital_status: "Married",
      education: "Post Graduate",
      monthly_salary: 125000,
      employment_type: "Private",
      years_of_employment: 8,
      company_type: "MNC",
      house_type: "Own",
      monthly_rent: 0,
      family_size: 3,
      dependents: 1,
      school_fees: 5000,
      college_fees: 0,
      travel_expenses: 6000,
      groceries_utilities: 15000,
      other_monthly_expenses: 4000,
      existing_loans: "No",
      current_emi_amount: 0,
      credit_score: 780,
      bank_balance: 350000,
      emergency_fund: 150000,
      emi_scenario: "Personal Loan EMI",
      requested_amount: 300000,
      requested_tenure: 24,
    },
  },
  {
    id: "first_time",
    name: "First-Time Buyer",
    badge: "Expected: Eligible",
    description: "Young graduate starting career, renting, purchasing home appliances.",
    data: {
      age: 26,
      gender: "Female",
      marital_status: "Single",
      education: "Graduate",
      monthly_salary: 55000,
      employment_type: "Private",
      years_of_employment: 3,
      company_type: "Private Ltd",
      house_type: "Rented",
      monthly_rent: 10000,
      family_size: 1,
      dependents: 0,
      school_fees: 0,
      college_fees: 0,
      travel_expenses: 3000,
      groceries_utilities: 8000,
      other_monthly_expenses: 3000,
      existing_loans: "No",
      current_emi_amount: 0,
      credit_score: 730,
      bank_balance: 85000,
      emergency_fund: 40000,
      emi_scenario: "Home Appliances EMI",
      requested_amount: 75000,
      requested_tenure: 12,
    },
  },
  {
    id: "self_employed",
    name: "Self-Employed Moderate Risk",
    badge: "Expected: High Risk",
    description: "Business owner with active vehicle loan and near-prime credit (670).",
    data: {
      age: 41,
      gender: "Male",
      marital_status: "Married",
      education: "Graduate",
      monthly_salary: 80000,
      employment_type: "Self-employed",
      years_of_employment: 12,
      company_type: "Private Ltd",
      house_type: "Rented",
      monthly_rent: 16000,
      family_size: 4,
      dependents: 2,
      school_fees: 8000,
      college_fees: 0,
      travel_expenses: 7000,
      groceries_utilities: 18000,
      other_monthly_expenses: 5000,
      existing_loans: "Yes",
      current_emi_amount: 14000,
      credit_score: 670,
      bank_balance: 90000,
      emergency_fund: 30000,
      emi_scenario: "Vehicle EMI",
      requested_amount: 400000,
      requested_tenure: 36,
    },
  },
  {
    id: "high_leverage",
    name: "Strained Cashflow",
    badge: "Expected: Not Eligible",
    description: "High existing EMI load and subprime credit score (540).",
    data: {
      age: 29,
      gender: "Male",
      marital_status: "Single",
      education: "High School",
      monthly_salary: 32000,
      employment_type: "Private",
      years_of_employment: 2,
      company_type: "Startup",
      house_type: "Rented",
      monthly_rent: 9000,
      family_size: 2,
      dependents: 1,
      school_fees: 2000,
      college_fees: 0,
      travel_expenses: 4000,
      groceries_utilities: 8000,
      other_monthly_expenses: 3000,
      existing_loans: "Yes",
      current_emi_amount: 11000,
      credit_score: 540,
      bank_balance: 15000,
      emergency_fund: 5000,
      emi_scenario: "E-commerce Shopping EMI",
      requested_amount: 120000,
      requested_tenure: 18,
    },
  },
];
